### ISSUE TITLE
Very happy to see this proposal

### ISSUE THREAD

**Issue by kdeqc** [DCtheTall/CHIPS#8]
I just wanted to show support for this proposal.  This would be very helpful for a lot of Salesforce's SaaS services where we're just trying to provide functionality on behalf of a first-party.

**Comment by krgovind** [comment]
Thanks for your support, @kdeqc ! I pointed to Saleforce's statement from our [WICG Discourse thread](https://discourse.wicg.io/t/proposal-cookies-having-independent-partitioned-state-chips/5290/3).
